export const STACK_SCREENS = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  PROFILE_EDIT: 'PROFILE_EDIT',
  PUBLICK_PROFILE: ':PUBLICK_PROFILE',
};
export const BOTTOM_TAB_SCREEN = {
  FEED: 'Feed',
  UPLOAD_POST: 'UPLOAD_POST',
  MY_PROFILE: 'MY_PROFILE',
};
export const AUTH_STACK_SCREEN = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
};
export const PARAM_ROUTE_SCREEM = {
  PUBLICK_PROFILE: 'PUBLICK_PROFILE',
};
